### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by watkin36** [watkin36/codelab-sinatra-assets-and-layouts#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http:// https://shrouded-cliffs-3432.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/sinatra-assets-and-layouts/1) criteria:
- [x] The code from the previous Sinatra project is copied into this project folder
- [x] You have more than one view file served to more than one route
- [x] A `.css` and `.js` file are included on every page via a `link` and `script` element, respectively (make sure those files have some effect on the page so that we know it worked)
- [x] A `layout.erb` file is used to DRY up your HTML
- [x] There are not _any_ unnecessarily duplicated lines of code between view files

**Comment by chrisvfritz** [comment]
Everything looks good, apart from one line of duplicated code:
- It looks like [in your profile.erb view](https://github.com/watkin36/codelab-sinatra-assets-and-layouts/blob/master/views/profile.erb#L39), you've included a `script` tag that is already included in your layout. Since `layout.erb` is already including it, let's remove it from `profile.erb`.

There are also a few more non-criteria changes I'd like made to get this project to _super_ ship-worthy status. :smiley:
- It looks like whenever someone submits a form to contact the person who made the dating profile, [it always sends the email to you](https://github.com/watkin36/codelab-sinatra-assets-and-layouts/blob/master/views/profile.erb#L29). Instead, what would you think about collecting an email address in the initial form and using that to configure which email address the form is sent to?
- I see some `.DS_Store` files throughout this project on GitHub. OS X generates these and they don't _break_ anything, but they do clutter up the codebase. Check out [this question on StackOverflow](http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository) to learn how to remove them and make sure they don't get checked into `git` in the future.
- It looks like [your styles](https://github.com/watkin36/codelab-sinatra-assets-and-layouts/blob/master/public/main.css) have an increased base indentation, with an empty line at the top of the file. I would dedent (i.e. unindent) everything in that file so that the lowest level of indentation is 0 (let me know if that makes sense to you). Then unless you have a good reason for the empty line at the top, I would remove that too.

Let me know if you have any questions and I'll be happy to give more detailed feedback on any item. :christmas_tree:

**Comment by watkin36** [comment]
I've corrected the indentation and deleted the duplicated code. Pretty sure I've also made the fix to stop .DS_store files from uploading to GitHub.

I made a few attempts to have the send-to e-mail address be collected on the first page and then used on the second page.  I wasn't able to figure out how to configure the email / form setting though. What should I be looking at for that? I'm looking through JQuery materials now, but any direction would be appreciated (I haven't gone down the JQuery part of the lesson path yet).

Thanks, and I hope you had a great Christmas!

**Comment by chrisvfritz** [comment]
Both `profile.erb` and `style.css` are looking very nice now! :balloon: 

I'm still seeing the `.DS_Store` files though. Did you try the instructions in [this answer on Stack Overflow](http://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository#answer-107921)? You'll know the `.DS_Store` files are really gone when you don't see them on [your project's GitHub page](https://github.com/watkin36/codelab-sinatra-assets-and-layouts).

As for collecting an email from users and embedding it in the form, you shouldn't need JavaScript at all actually! You can inject the email from `params`, just like you're doing for every other field. On [this line](https://github.com/watkin36/codelab-sinatra-assets-and-layouts/blob/master/views/profile.erb#L29), you can see that your email address (`watkin36@yahoo.com`) is hard-coded into the page. Just like you did to display the image, you can use Ruby to inject an email address supplied by the user, in place of your own.

Let me know if that makes sense - but worst case, I'll see you tomorrow!

**Comment by watkin36** [comment]
Should be shipit worthy now! Took care of the DS_Store files and the form submission too!
Thanks!

**Comment by chrisvfritz** [comment]
Woohoo! :shipit:
